[package]
name = "nsbt"
version = "0.1.0"
authors = ["Antoine Gourlay <antoine@gourlay.fr>"]

[dependencies]
tokio-proto = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
futures = "0.1"
rustyline = "1.0"
json = "0.11"
